spring:
  application:
    name: employee-service
server:
  servlet:
    context-path: /employee
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true