spring:
  application:
    name: product-service
server:
  servlet:
    context-path: /product
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true